const projects = [
  {
    id: 0,
    title: 'The Scramble Cook',
    desc: 'Personal app that builds a random weekly menu from home recipes. Pulls from a cloud datasource to end the daily "what are we having?" chore.',
    image: '/images/thumbnails/scramble-cook.png',
    video: '/images/thumbnails/scramble-cook.mp4',
    link: 'https://github.com/ffmc/scramble-cook',
    thumbH: 1100,
  },
  {
    id: 1,
    title: "World's Happiness in 2026",
    desc: 'Interactive D3.js exploration of global wellbeing scores across 147 countries using 2026 Gallup data.',
    image: '/images/thumbnails/world-happiness-2026.png',
    link: 'https://ffmc.github.io/world_happiness/',
    thumbH: 1100,
  },
  {
    id: 2,
    title: 'Predictions',
    desc: 'A scrollytelling data story exploring the accuracy of human predictions across global forecasting platforms.',
    image: '/images/thumbnails/predictions.png',
    link: 'https://ffmc.github.io/predictions/',
    thumbH: 1100,
  },
  {
    id: 3,
    title: 'Debate Room',
    desc: 'Cinematic HTML explainer presenting Debate Room, a next-generation Business Intelligence tool.',
    image: '/images/thumbnails/debate-room.png',
    link: 'https://ffmc.github.io/Debate-Room/',
    thumbH: 900,

  },
  {
    id: 4,
    title: 'Lens',
    desc: 'AI-powered analytics dashboard with intelligent insight cards and anomaly detection for business data.',
    image: '/images/thumbnails/lens-dashboard.png',
    link: 'https://ffmc.github.io/lens/',
    thumbH: 900,
  },
  {
    id: 5,
    title: 'Benefits of Working Remotely',
    desc: 'Showing the top benefits cited by 3,500 remote workers — led by flexible schedule, location, and no commute.',
    image: '/images/thumbnails/benefits-of-working-remotely.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/HorizontalSankeyTemplate_15969888927470/Final',
    thumbH: 927,
  },
  {
    id: 6,
    title: 'National Parks | #IronViz 2021',
    desc: 'Highlights of US National Parks for the IronViz 2021 competition.',
    image: '/images/thumbnails/national-parks-ironviz-2021.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/NationalParksIronViz2021/NationalParks',
    thumbH: 1500,
  },
  {
    id: 7,
    title: 'Leeds United',
    desc: "Tracking Leeds United FC's match victories and performance across football league seasons.",
    image: '/images/thumbnails/leeds-united.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/LeedsUnited/Victories_Dashboard',
    thumbH: 2018,
  },
  {
    id: 8,
    title: 'Women in Power',
    desc: 'Comparing the share of women in government, parliament, and leadership roles by country.',
    image: '/images/thumbnails/women-in-power.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/Womeninpower/Final',
    thumbH: 1500,
  },
  {
    id: 9,
    title: 'The Texas Blackout',
    desc: 'Visualizing the 2021 Texas power grid failure, showing outages, temperatures, and human impact across the state.',
    image: '/images/thumbnails/the-texas-blackout.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/TheTexasBlackout/Final',
    thumbH: 927,
  },
  {
    id: 10,
    title: 'Cocoa Import',
    desc: 'Analysing global cocoa bean import volumes and trade flows between producing and consuming countries.',
    image: '/images/thumbnails/cocoa-import.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/CocoaImport/Final',
    thumbH: 837,
  },
  {
    id: 11,
    title: 'World Happiness Report',
    desc: 'Maps global happiness scores and their key drivers — GDP, social support, and freedom — across countries.',
    image: '/images/thumbnails/world-happiness-report.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/WorldHappinessReport_16227727330990/WorldHappiness',
    thumbH: 1955,
  },
  {
    id: 12,
    title: 'Metros of the World',
    desc: "Visualizing the station count, annual ridership, and network length of the world's major metro systems.",
    image: '/images/thumbnails/metros-of-the-world.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/MetrosoftheWorld/MetrosoftheWorld',
    thumbH: 1500,
  },
  {
    id: 14,
    title: "Arsenal's Premier League Performance",
    desc: "Charting Arsenal FC's match results, goals scored, and league standing across Premier League seasons.",
    image: '/images/thumbnails/arsenals-premier-league-performance.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/ArsenalsPremierLeaguePerformance/Final',
    thumbH: 927,
  },
  {
    id: 15,
    title: 'Digital Gender Gap',
    desc: 'Comparing internet access and digital skill levels between men and women across countries.',
    image: '/images/thumbnails/digital-gender-gap.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/DigitalGenderGap_16043767070660/Final',
    thumbH: 927,
  },
  {
    id: 16,
    title: 'Apparel Import',
    desc: 'Analysing global clothing and textile import volumes by country and trade corridor.',
    image: '/images/thumbnails/apparel-import.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/ApparelImport/Final',
    thumbH: 927,
  },
  {
    id: 17,
    title: 'Indian Cricket Stats',
    desc: 'Tracking batting averages, bowling figures, and win/loss records of the Indian national cricket team.',
    image: '/images/thumbnails/indian-cricket-stats.png',
    link: 'https://public.tableau.com/app/profile/francisco4773/viz/IndianCricketStats/Final',
    thumbH: 927,
  },
]

export default projects
