const GH = 'https://raw.githubusercontent.com/ffmc/website/main/images'

const projects = [
  {
    id: 1,
    type: 'Data Visualization',
    title: 'Dashboards Changed Everything',
    desc: 'Visual narrative on how dashboards transformed business decision-making — from spreadsheets to always-on intelligence.',
    image: `${GH}/debate-room.png`,
    ratio: [16, 9],
    year: '2024',
    link: null,
  },
  {
    id: 2,
    type: 'Analytics Platform',
    title: 'LENS Intelligence Surface',
    desc: 'Real-time anomaly detection and signal surfacing for enterprise datasets. Surfaces what matters before you know to look.',
    image: `${GH}/lens.png`,
    ratio: [2287, 1302],
    year: '2024',
    link: null,
  },
  {
    id: 3,
    type: 'Data Story',
    title: 'We Are Bad at Predicting',
    desc: 'Scrollytelling piece analyzing 2,129 resolved predictions from Metaculus to understand human forecasting bias at scale.',
    image: `${GH}/predictions.png`,
    ratio: [8, 5],
    year: '2023',
    link: null,
  },
  {
    id: 4,
    type: 'Platform',
    title: 'Executive KPI Platform',
    desc: 'Self-service analytics giving 200+ stakeholders governed, real-time access to the metrics that drive business decisions.',
    image: null,
    ratio: [16, 9],
    year: '2023',
    ph: ['#1C88CC', '#3B64A7'],
    link: null,
  },
  {
    id: 5,
    type: 'Data Engineering',
    title: 'Real-time Event Pipeline',
    desc: 'End-to-end streaming pipeline processing 500K+ events per day — from raw ingestion through dbt transformation to viz.',
    image: null,
    ratio: [16, 9],
    year: '2022',
    ph: ['#3B64A7', '#1C2850'],
    link: null,
  },
  {
    id: 6,
    type: 'Infrastructure',
    title: 'Data Governance Framework',
    desc: 'Enterprise-wide data catalog covering 3,000+ datasets across all business units, enabling trusted self-service analytics.',
    image: null,
    ratio: [4, 3],
    year: '2022',
    ph: ['#FF5C00', '#3B64A7'],
    link: null,
  },
]

export default projects
